### PR TITLE
Fixed accessibility (color contast)

### PR DESCRIPTION
**Pull request by aimemalaika**
## What does this PR do?
This PR is raised to fix the website accessibility
## Description of the task to be completed
- Page titles - added a favicon to the website https://github.com/aimemalaika/portofolio/pull/10/commits/8141a353c4fe12152432f505abd2ceca08df0e52#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R13
- Image text alternatives** (alt text)  - no issues found
- Text headings  - no issues found
- Color contrast - Fixed text colors, I removed the assigned color https://github.com/aimemalaika/portofolio/pull/10/commits/287ff3d18f0698d4e706a119c5a9ee22f4ab017f#diff-a72d4ee198d130c997b203ecb2f5c54d84617b3cdf7bd9eaab804be78e2709aeL521
- Resize  - no issues found
- Interaction Moving content - no issues found
- Multimedia  - no issues found
- The basic structure of the page   - no issues found
- Names and labels - added name to the button with no content https://github.com/aimemalaika/portofolio/pull/10/commits/b399ad5400827fce1807c3bd3a31c2b3c78698b0#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R80
## How should it be tested
- clone the repository\
  `git clone https://github.com/aimemalaika/portofolio.git`
- navigate to the folder\
  `cd portofolio`
- checkout the feature\
  `feature-website-accessibility`
Screen Shot 2021-12-07 at 11 20 36

### CODE REVIEW

**Comment by ShoiraTa** [comment]
Hi team, 

:thumbsup: This is good to make it this far, your report looks professional.

However, there are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [ ] According to project retirements, you have to include more points in description of your pull request.: ⬇️ 

image

Please notice that `If everything was ok, make a statement about that (e.g. "Page titles - no issues found")`.
And if you found issues, please describe them and link to the corresponding line of code in your pull request changes, here is how you can add [links](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148) in this case

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aimemalaika** [comment]
Hello @ShoiraTa , You mean i should describe what I did in my PR ?

**Comment by ShoiraTa** [comment]
Hello again, You can list the following items in your PR and write the detected issue if no issue, then write no issue : 
- **Page titles** - no issues found;
- **mage text alternatives** - some images didn't have `alt` text [link](link);
- **Text headings** -  no issues found;
- **Color contrast** - your report
- **Resize** -  your report
- **Interaction**-  your report
- **Moving content** -  your report
- **Multimedia**-  your report
- **The basic structure of the page** -  your report

**Comment by ShoiraTa** [comment]
You can copy this as a template:
```
- **Page titles** - no issues found;
- **mage text alternatives** - some images didn't have `alt` text [link](link);
- **Text headings** -  no issues found;
- **Color contrast** - your report
- **Resize** -  your report
- **Interaction**-  your report
- **Moving content** -  your report
- **Multimedia**-  your report
- **The basic structure of the page** -  your report
```

**Review by andersonlebon — APPROVED** [review]
Hi @aimemalaika 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
